# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./test_redisconnection.h \
    ./test_redisconnectionsmanager.h \
    ../demo/RedisKeyItem.h \
    ../demo/RedisKeyNamespace.h \
    ../demo/RedisServerDbItem.h \
    ../demo/RedisServerItem.h \
    ../demo/network/qxtnetwork.h \
    ../demo/network/qxtsshchannel.h \
    ../demo/network/qxtsshchannel_p.h \
    ../demo/network/qxtsshclient.h \
    ../demo/network/qxtsshclient_p.h \
    ../demo/network/qxtsshprocess.h \
    ../demo/network/qxtsshtcpsocket.h \
    ../demo/redisconnection.h \
    ../demo/RedisConnectionAbstract.h \
    ../demo/RedisConnectionConfig.h \
    ../demo/RedisConnectionsManager.h \
    ../demo/RedisException.h \
    ../demo/RedisConnectionOverSsh.h
SOURCES += ./main.cpp \
    ./test_redisconnection.cpp \
    ./test_redisconnectionsmanager.cpp \
    ../demo/network/qxtsshchannel.cpp \
    ../demo/network/qxtsshclient.cpp \
    ../demo/network/qxtsshprocess.cpp \
    ../demo/network/qxtsshtcpsocket.cpp \
    ../demo/redisconnection.cpp \
    ../demo/RedisConnectionAbstract.cpp \
    ../demo/RedisConnectionConfig.cpp \
    ../demo/RedisConnectionOverSsh.cpp \
    ../demo/RedisConnectionsManager.cpp \
    ../demo/RedisKeyItem.cpp \
    ../demo/RedisKeyNamespace.cpp \
    ../demo/RedisServerDbItem.cpp \
    ../demo/RedisServerItem.cpp
