/**
 * RESP.app Extension server
 * RESP.app Extension Server API allows you to extend RESP.app with your custom data formatters
 *
 * The version of the OpenAPI document: 2022.0-preview1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIInline_response_400.h
 *
 * 
 */

#ifndef OAIInline_response_400_H
#define OAIInline_response_400_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace RespExtServer {

class OAIInline_response_400 : public OAIObject {
public:
    OAIInline_response_400();
    OAIInline_response_400(QString json);
    ~OAIInline_response_400() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getError() const;
    void setError(const QString &error);
    bool is_error_Set() const;
    bool is_error_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString error;
    bool m_error_isSet;
    bool m_error_isValid;
};

} // namespace RespExtServer

Q_DECLARE_METATYPE(RespExtServer::OAIInline_response_400)

#endif // OAIInline_response_400_H
